// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class AddTerminalPublicKey extends BankRequest {
    private String key;

    public AddTerminalPublicKey(String key) {
        this.key = key;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/terminal" + "/keys";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (key != null) {
                put("key", key);
            }
        }};
    }

    public final TerminalServerKey send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(TerminalServerKey.class, accessToken);
    }
}
