// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateTransactionWithBill extends BankRequest {
    private String requestId;
    private String billId;
    private String accountId;
    private Double amount;
    private String couponId;
    private String strategy;

    public CreateTransactionWithBill(String requestId, String billId) {
        this.requestId = requestId;
        this.billId = billId;
    }

    public CreateTransactionWithBill accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    public CreateTransactionWithBill amount(Double amount) {
        this.amount = amount;
        return this;
    }

    public CreateTransactionWithBill couponId(String couponId) {
        this.couponId = couponId;
        return this;
    }

    public CreateTransactionWithBill strategy(String strategy) {
        this.strategy = strategy;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/transactions" + "/bill";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (requestId != null) {
                put("request_id", requestId);
            }
            if (billId != null) {
                put("bill_id", billId);
            }
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (amount != null) {
                put("amount", amount);
            }
            if (couponId != null) {
                put("coupon_id", couponId);
            }
            if (strategy != null) {
                put("strategy", strategy);
            }
        }};
    }

    public final UserTransactionWithFallback send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(UserTransactionWithFallback.class, accessToken);
    }
}
