// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateCheckTransaction extends BankRequest {
    private String requestId;
    private String checkId;
    private String accountId;
    private Integer topupQuotaId;

    public CreateCheckTransaction(String checkId) {
        this.checkId = checkId;
    }

    public CreateCheckTransaction requestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    public CreateCheckTransaction accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    public CreateCheckTransaction topupQuotaId(Integer topupQuotaId) {
        this.topupQuotaId = topupQuotaId;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/transactions" + "/check";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (requestId != null) {
                put("request_id", requestId);
            }
            if (checkId != null) {
                put("check_id", checkId);
            }
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (topupQuotaId != null) {
                put("topup_quota_id", topupQuotaId);
            }
        }};
    }

    public final UserTransactionWithFallback send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(UserTransactionWithFallback.class, accessToken);
    }
}
