// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateTransactionWithCashtray extends BankRequest {
    private String requestId;
    private String cashtrayId;
    private String accountId;
    private String couponId;
    private String strategy;
    private Integer topupQuotaId;

    public CreateTransactionWithCashtray(String requestId, String cashtrayId) {
        this.requestId = requestId;
        this.cashtrayId = cashtrayId;
    }

    public CreateTransactionWithCashtray accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    public CreateTransactionWithCashtray couponId(String couponId) {
        this.couponId = couponId;
        return this;
    }

    public CreateTransactionWithCashtray strategy(String strategy) {
        this.strategy = strategy;
        return this;
    }

    public CreateTransactionWithCashtray topupQuotaId(Integer topupQuotaId) {
        this.topupQuotaId = topupQuotaId;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/transactions" + "/cashtray";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (requestId != null) {
                put("request_id", requestId);
            }
            if (cashtrayId != null) {
                put("cashtray_id", cashtrayId);
            }
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (couponId != null) {
                put("coupon_id", couponId);
            }
            if (strategy != null) {
                put("strategy", strategy);
            }
            if (topupQuotaId != null) {
                put("topup_quota_id", topupQuotaId);
            }
        }};
    }

    public final UserTransactionWithFallback send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(UserTransactionWithFallback.class, accessToken);
    }
}
