// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.Parameters.Product;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateCashtray extends BankRequest {
    private Double amount;
    private String description;
    private Integer expiresIn;
    private Product[] products;
    private String metadata;

    public CreateCashtray(double amount) {
        this.amount = amount;
    }

    public CreateCashtray description(String description) {
        this.description = description;
        return this;
    }

    public CreateCashtray expiresIn(Integer expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }

    public CreateCashtray products(Product[] products) {
        this.products = products;
        return this;
    }

    public CreateCashtray metadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/cashtrays";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (amount != null) {
                put("amount", amount);
            }
            if (description != null) {
                put("description", description);
            }
            if (expiresIn != null) {
                put("expires_in", expiresIn);
            }
            if (products != null) {
                put("products", products);
            }
            if (metadata != null) {
                put("metadata", metadata);
            }
        }};
    }

    public final Cashtray send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(Cashtray.class, accessToken);
    }
}
