// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateBankPay extends BankRequest {
    private String privateMoneyId;
    private String callbackUrl;
    private String kana;
    private String userId;

    public CreateBankPay(String userId, String privateMoneyId, String callbackUrl) {
        this.userId = userId;
        this.privateMoneyId = privateMoneyId;
        this.callbackUrl = callbackUrl;
    }

    public CreateBankPay kana(String kana) {
        this.kana = kana;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/users" + "/" + this.userId + "/banks";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (privateMoneyId != null) {
                put("private_money_id", privateMoneyId);
            }
            if (callbackUrl != null) {
                put("callback_url", callbackUrl);
            }
            if (kana != null) {
                put("kana", kana);
            }
        }};
    }

    public final BankPaySession send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(BankPaySession.class, accessToken);
    }
}
