// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateBill extends BankRequest {
    private Double amount;
    private String accountId;
    private String[] additionalAccountIds;
    private String description;
    private Boolean isOnetime;
    private Double minAmount;
    private Double maxAmount;
    private Product[] products;
    private String metadata;

    public CreateBill() {
    }

    public CreateBill amount(Double amount) {
        this.amount = amount;
        return this;
    }

    public CreateBill accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    public CreateBill additionalAccountIds(String[] additionalAccountIds) {
        this.additionalAccountIds = additionalAccountIds;
        return this;
    }

    public CreateBill description(String description) {
        this.description = description;
        return this;
    }

    public CreateBill isOnetime(Boolean onetime) {
        isOnetime = onetime;
        return this;
    }

    public CreateBill minAmount(Double minAmount) {
        this.minAmount = minAmount;
        return this;
    }

    public CreateBill maxAmount(Double maxAmount) {
        this.maxAmount = maxAmount;
        return this;
    }

    public CreateBill products(Product[] products) {
        this.products = products;
        return this;
    }

    public CreateBill metadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/bills";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (amount != null) {
                put("amount", amount);
            }
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (additionalAccountIds != null) {
                put("additional_account_ids", additionalAccountIds);
            }
            if (description != null) {
                put("description", description);
            }
            if (isOnetime != null) {
                put("is_onetime", isOnetime);
            }
            if (minAmount != null) {
                put("min_amount", minAmount);
            }
            if (maxAmount != null) {
                put("max_amount", maxAmount);
            }
            if (products != null) {
                put("products", products);
            }
            if (metadata != null) {
                put("metadata", metadata);
            }
        }};
    }

    public final Bill send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(Bill.class, accessToken);
    }
}
