// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateCreditCard extends BankRequest {
    private String token;
    private Boolean isCardholderNameSpecified;
    private String organizationCode;
    private String userId;

    public CreateCreditCard(String userId, String token, String organizationCode) {
        this.userId = userId;
        this.token = token;
        this.organizationCode = organizationCode;
    }

    public CreateCreditCard isCardholderNameSpecified(Boolean cardholderNameSpecified) {
        isCardholderNameSpecified = cardholderNameSpecified;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/users" + "/" + this.userId + "/cards";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (token != null) {
                put("token", token);
            }
            if (isCardholderNameSpecified != null) {
                put("is_cardholder_name_specified", isCardholderNameSpecified);
            }
            if (organizationCode != null) {
                put("organization_code", organizationCode);
            }
        }};
    }

    public final CreditCard send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(CreditCard.class, accessToken);
    }
}
