// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateAccount extends BankRequest {
    private String name;
    private String privateMoneyId;
    private String externalId;

    public CreateAccount(String privateMoneyId) {
        this.privateMoneyId = privateMoneyId;
    }

    public CreateAccount name(String name) {
        this.name = name;
        return this;
    }

    public CreateAccount externalId(String externalId) {
        this.externalId = externalId;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/accounts";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (name != null) {
                put("name", name);
            }
            if (privateMoneyId != null) {
                put("private_money_id", privateMoneyId);
            }
            if (externalId != null) {
                put("external_id", externalId);
            }
        }};
    }

    public final AccountDetail send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(AccountDetail.class, accessToken);
    }
}
