// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateJihanpiTransaction extends BankRequest {
    private String nfcTagId;
    private String accountId;
    private String requestId;
    private String strategy;

    public CreateJihanpiTransaction(String nfcTagId, String accountId) {
        this.nfcTagId = nfcTagId;
        this.accountId = accountId;
    }

    public CreateJihanpiTransaction requestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    public CreateJihanpiTransaction strategy(String strategy) {
        this.strategy = strategy;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/jihanpi-transactions";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (nfcTagId != null) {
                put("nfc_tag_id", nfcTagId);
            }
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (requestId != null) {
                put("request_id", requestId);
            }
            if (strategy != null) {
                put("strategy", strategy);
            }
        }};
    }

    public final JihanpiTransaction send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(JihanpiTransaction.class, accessToken);
    }
}
