// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.Parameters.Product;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CreateCpmTransaction extends BankRequest {
    private String requestId;
    private String cpmToken;
    private String accountId;
    private Double amount;
    private Product[] products;
    private Integer topupQuotaId;

    public CreateCpmTransaction(String requestId, String cpmToken, double amount) {
        this.requestId = requestId;
        this.cpmToken = cpmToken;
        this.amount = amount;
    }

    public CreateCpmTransaction accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    public CreateCpmTransaction products(Product[] products) {
        this.products = products;
        return this;
    }

    public CreateCpmTransaction topupQuotaId(Integer topupQuotaId) {
        this.topupQuotaId = topupQuotaId;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/transactions" + "/cpm";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (requestId != null) {
                put("request_id", requestId);
            }
            if (cpmToken != null) {
                put("cpm_token", cpmToken);
            }
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (amount != null) {
                put("amount", amount);
            }
            if (products != null) {
                put("products", products);
            }
            if (topupQuotaId != null) {
                put("topup_quota_id", topupQuotaId);
            }
        }};
    }

    public final UserTransactionWithFallback send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(UserTransactionWithFallback.class, accessToken);
    }
}
