// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;

public class CreditWithCreditCardMembership extends BankRequest {
    private String userId;
    private String cardRegisteredAt;
    private String cardUuid;
    private String organizationCode;

    public CreditWithCreditCardMembership(String userId) {
        this.userId = userId;
    }

    public CreditWithCreditCardMembership cardRegisteredAt(String cardRegisteredAt) {
        this.cardRegisteredAt = cardRegisteredAt;
        return this;
    }

    public CreditWithCreditCardMembership cardUuid(String cardUuid) {
        this.cardUuid = cardUuid;
        return this;
    }

    public CreditWithCreditCardMembership organizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/veritrans" + "/card-authorize" + "/credit-with-membership";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (userId != null) {
                put("user_id", userId);
            }
            if (cardRegisteredAt != null) {
                put("card_registered_at", cardRegisteredAt);
            }
            if (cardUuid != null) {
                put("card_uuid", cardUuid);
            }
            if (organizationCode != null) {
                put("organization_code", organizationCode);
            }
        }};
    }

    public final String send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(String.class, accessToken);
    }
}
