// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class CVSAuthorizeRequest extends BankRequest {
    private String serviceOptionType;
    private Integer amount;
    private String name1;
    private String name2;
    private String tel;
    private Integer topupQuotaId;
    private String accountId;

    public CVSAuthorizeRequest(String accountId, String serviceOptionType, int amount, String name1, String name2, String tel) {
        this.accountId = accountId;
        this.serviceOptionType = serviceOptionType;
        this.amount = amount;
        this.name1 = name1;
        this.name2 = name2;
        this.tel = tel;
    }

    public CVSAuthorizeRequest topupQuotaId(Integer topupQuotaId) {
        this.topupQuotaId = topupQuotaId;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId + "/cvs";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (serviceOptionType != null) {
                put("service_option_type", serviceOptionType);
            }
            if (amount != null) {
                put("amount", amount);
            }
            if (name1 != null) {
                put("name1", name1);
            }
            if (name2 != null) {
                put("name2", name2);
            }
            if (tel != null) {
                put("tel", tel);
            }
            if (topupQuotaId != null) {
                put("topup_quota_id", topupQuotaId);
            }
        }};
    }

    public final CVSAuthorization send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(CVSAuthorization.class, accessToken);
    }
}
