// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.Responses.NoContent;

public class DeleteBank extends BankRequest {
    private String bankId;
    private String userId;

    public DeleteBank(String userId, String bankId) {
        this.userId = userId;
        this.bankId = bankId;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.DELETE;
    }

    @Override
    public String path() {
        return "/users" + "/" + this.userId + "/banks";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (bankId != null) {
                put("bank_id", bankId);
            }
        }};
    }

    public final NoContent send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(NoContent.class, accessToken);
    }
}
