// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetAccountBalances extends BankRequest {
    private String accountId;
    private String before;
    private String after;
    private Integer perPage;
    private BooleanString expired;

    public GetAccountBalances(String accountId, BooleanString expired) {
        this.accountId = accountId;
        this.expired = expired;
    }

    public GetAccountBalances before(String before) {
        this.before = before;
        return this;
    }

    public GetAccountBalances after(String after) {
        this.after = after;
        return this;
    }

    public GetAccountBalances perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId + "/balances";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (before != null) {
                put("before", before);
            }
            if (after != null) {
                put("after", after);
            }
            if (perPage != null) {
                put("per_page", perPage);
            }
            if (expired != null) {
                put("expired", expired);
            }
        }};
    }

    public final PaginatedAccountBalances send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(PaginatedAccountBalances.class, accessToken);
    }
}
