// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetAccountTopupQuotas extends BankRequest {
    private String accountId;
    private String status;
    private Boolean showExpiredForFixedPeriod;
    private Boolean showStartedQuotas;
    private Boolean isWithinApplicablePeriod;
    private Boolean isUsableAmountLeft;

    public GetAccountTopupQuotas(String accountId) {
        this.accountId = accountId;
    }

    public GetAccountTopupQuotas status(String status) {
        this.status = status;
        return this;
    }

    public GetAccountTopupQuotas showExpiredForFixedPeriod(Boolean showExpiredForFixedPeriod) {
        this.showExpiredForFixedPeriod = showExpiredForFixedPeriod;
        return this;
    }

    public GetAccountTopupQuotas showStartedQuotas(Boolean showStartedQuotas) {
        this.showStartedQuotas = showStartedQuotas;
        return this;
    }

    public GetAccountTopupQuotas isWithinApplicablePeriod(Boolean withinApplicablePeriod) {
        isWithinApplicablePeriod = withinApplicablePeriod;
        return this;
    }

    public GetAccountTopupQuotas isUsableAmountLeft(Boolean usableAmountLeft) {
        isUsableAmountLeft = usableAmountLeft;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId + "/topup-quotas";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (status != null) {
                put("status", status);
            }
            if (showExpiredForFixedPeriod != null) {
                put("show_expired_for_fixed_period", showExpiredForFixedPeriod);
            }
            if (showStartedQuotas != null) {
                put("show_started_quotas", showStartedQuotas);
            }
            if (isWithinApplicablePeriod != null) {
                put("is_within_applicable_period", isWithinApplicablePeriod);
            }
            if (isUsableAmountLeft != null) {
                put("is_usable_amount_left", isUsableAmountLeft);
            }
        }};
    }

    public final AccountTopupQuotas send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(AccountTopupQuotas.class, accessToken);
    }
}
