// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetAccountCoupons extends BankRequest {
    private Uuid accountId;
    private BooleanString isAvailable;
    private String before;
    private String after;
    private Integer perPage;

    public GetAccountCoupons(Uuid accountId, BooleanString isAvailable) {
        this.accountId = accountId;
        this.isAvailable = isAvailable;
    }

    public GetAccountCoupons before(String before) {
        this.before = before;
        return this;
    }

    public GetAccountCoupons after(String after) {
        this.after = after;
        return this;
    }

    public GetAccountCoupons perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId + "/coupons";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (isAvailable != null) {
                put("is_available", isAvailable);
            }
            if (before != null) {
                put("before", before);
            }
            if (after != null) {
                put("after", after);
            }
            if (perPage != null) {
                put("per_page", perPage);
            }
        }};
    }

    public final PaginatedAccountCoupons send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(PaginatedAccountCoupons.class, accessToken);
    }
}
