// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetAccount extends BankRequest {
    private Uuid accountId;

    public GetAccount(Uuid accountId) {
        this.accountId = accountId;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId;
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
        }};
    }

    public final AccountDetail send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(AccountDetail.class, accessToken);
    }
}
