// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetAccountTransfers extends BankRequest {
    private Uuid accountId;
    private String before;
    private String after;
    private Integer perPage;

    public GetAccountTransfers(Uuid accountId) {
        this.accountId = accountId;
    }

    public GetAccountTransfers before(String before) {
        this.before = before;
        return this;
    }

    public GetAccountTransfers after(String after) {
        this.after = after;
        return this;
    }

    public GetAccountTransfers perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId + "/transfers";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (before != null) {
                put("before", before);
            }
            if (after != null) {
                put("after", after);
            }
            if (perPage != null) {
                put("per_page", perPage);
            }
        }};
    }

    public final PaginatedAccountTransfers send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(PaginatedAccountTransfers.class, accessToken);
    }
}
