// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetBill extends BankRequest {
    private String billId;
    private String privateMoneyId;

    public GetBill(String billId) {
        this.billId = billId;
    }

    public GetBill privateMoneyId(String privateMoneyId) {
        this.privateMoneyId = privateMoneyId;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/bills" + "/" + this.billId;
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (privateMoneyId != null) {
                put("private_money_id", privateMoneyId);
            }
        }};
    }

    public final BillWithAdditionalPrivateMoneys send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(BillWithAdditionalPrivateMoneys.class, accessToken);
    }
}
