// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetBillTransactions extends BankRequest {
    private String billId;
    private String before;
    private String after;
    private Integer perPage;

    public GetBillTransactions(String billId) {
        this.billId = billId;
    }

    public GetBillTransactions before(String before) {
        this.before = before;
        return this;
    }

    public GetBillTransactions after(String after) {
        this.after = after;
        return this;
    }

    public GetBillTransactions perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/bills" + "/" + this.billId + "/transactions";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (before != null) {
                put("before", before);
            }
            if (after != null) {
                put("after", after);
            }
            if (perPage != null) {
                put("per_page", perPage);
            }
        }};
    }

    public final PaginatedBillTransactions send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(PaginatedBillTransactions.class, accessToken);
    }
}
