// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetCashtrayAttempts extends BankRequest {
    private String cashtrayId;

    public GetCashtrayAttempts(String cashtrayId) {
        this.cashtrayId = cashtrayId;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/cashtrays" + "/" + this.cashtrayId + "/attempts";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
        }};
    }

    public final CashtrayAttempts send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(CashtrayAttempts.class, accessToken);
    }
}
