// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetCVSAuthorization extends BankRequest {
    private String accountId;
    private String orderId;

    public GetCVSAuthorization(String accountId, String orderId) {
        this.accountId = accountId;
        this.orderId = orderId;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId + "/cvs" + "/" + this.orderId;
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
        }};
    }

    public final CVSAuthorization send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(CVSAuthorization.class, accessToken);
    }
}
