// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetListOfShops extends BankRequest {
    private String privateMoneyId;
    private String userTagGroupItemId;
    private Uuid before;
    private Uuid after;
    private Integer perPage;

    public GetListOfShops(String privateMoneyId, Uuid before, Uuid after) {
        this.privateMoneyId = privateMoneyId;
        this.before = before;
        this.after = after;
    }

    public GetListOfShops userTagGroupItemId(String userTagGroupItemId) {
        this.userTagGroupItemId = userTagGroupItemId;
        return this;
    }

    public GetListOfShops perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/shops";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (privateMoneyId != null) {
                put("private_money_id", privateMoneyId);
            }
            if (userTagGroupItemId != null) {
                put("user_tag_group_item_id", userTagGroupItemId);
            }
            if (before != null) {
                put("before", before);
            }
            if (after != null) {
                put("after", after);
            }
            if (perPage != null) {
                put("per_page", perPage);
            }
        }};
    }

    public final PaginatedShops send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(PaginatedShops.class, accessToken);
    }
}
