// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetPrivateMoneyCoupons extends BankRequest {
    private Uuid privateMoneyId;
    private Uuid before;
    private Uuid after;
    private Integer perPage;

    public GetPrivateMoneyCoupons(Uuid privateMoneyId, Uuid before, Uuid after) {
        this.privateMoneyId = privateMoneyId;
        this.before = before;
        this.after = after;
    }

    public GetPrivateMoneyCoupons perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/private-moneys" + "/" + this.privateMoneyId + "/coupons";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (before != null) {
                put("before", before);
            }
            if (after != null) {
                put("after", after);
            }
            if (perPage != null) {
                put("per_page", perPage);
            }
        }};
    }

    public final PaginatedPrivateMoneyCoupons send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(PaginatedPrivateMoneyCoupons.class, accessToken);
    }
}
