// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetUserAccounts extends BankRequest {
    private String userId;
    private String before;
    private String after;
    private Integer perPage;

    public GetUserAccounts(String userId) {
        this.userId = userId;
    }

    public GetUserAccounts before(String before) {
        this.before = before;
        return this;
    }

    public GetUserAccounts after(String after) {
        this.after = after;
        return this;
    }

    public GetUserAccounts perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/users" + "/" + this.userId + "/accounts";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (before != null) {
                put("before", before);
            }
            if (after != null) {
                put("after", after);
            }
            if (perPage != null) {
                put("per_page", perPage);
            }
        }};
    }

    public final PaginatedUserAccounts send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(PaginatedUserAccounts.class, accessToken);
    }
}
