// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetUserTagGroupItems extends BankRequest {
    private String organizationCode;
    private String tagGroupId;
    private String before;
    private String after;
    private Integer perPage;

    public GetUserTagGroupItems(String organizationCode, String tagGroupId) {
        this.organizationCode = organizationCode;
        this.tagGroupId = tagGroupId;
    }

    public GetUserTagGroupItems before(String before) {
        this.before = before;
        return this;
    }

    public GetUserTagGroupItems after(String after) {
        this.after = after;
        return this;
    }

    public GetUserTagGroupItems perPage(Integer perPage) {
        this.perPage = perPage;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/user-tag-groups" + "/" + this.organizationCode + "/items";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (tagGroupId != null) {
                put("tag_group_id", tagGroupId);
            }
            if (before != null) {
                put("before", before);
            }
            if (after != null) {
                put("after", after);
            }
            if (perPage != null) {
                put("per_page", perPage);
            }
        }};
    }

    public final PaginatedUserTagGroupItems send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(PaginatedUserTagGroupItems.class, accessToken);
    }
}
