// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class GetVeritransMdkTokenApiKey extends BankRequest {
    private String organizationCode;

    public GetVeritransMdkTokenApiKey() {
    }

    public GetVeritransMdkTokenApiKey organizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.GET;
    }

    @Override
    public String path() {
        return "/veritrans" + "/mdk-token-api-key";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (organizationCode != null) {
                put("organization_code", organizationCode);
            }
        }};
    }

    public final VeritransMdkTokenApiKey send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(VeritransMdkTokenApiKey.class, accessToken);
    }
}
