// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class PatchAccountCouponDetail extends BankRequest {
    private Boolean isReceived;
    private String code;
    private String accountId;
    private String couponId;

    public PatchAccountCouponDetail(String accountId, String couponId) {
        this.accountId = accountId;
        this.couponId = couponId;
    }

    public PatchAccountCouponDetail isReceived(Boolean received) {
        isReceived = received;
        return this;
    }

    public PatchAccountCouponDetail code(String code) {
        this.code = code;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.PATCH;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId + "/coupons" + "/" + this.couponId;
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (isReceived != null) {
                put("is_received", isReceived);
            }
            if (code != null) {
                put("code", code);
            }
        }};
    }

    public final CouponDetail send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(CouponDetail.class, accessToken);
    }
}
