// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class SendToAccount extends BankRequest {
    private String receiverTerminalId;
    private String senderAccountId;
    private Double amount;
    private String description;
    private String accountId;

    public SendToAccount(String accountId, double amount) {
        this.accountId = accountId;
        this.amount = amount;
    }

    public SendToAccount receiverTerminalId(String receiverTerminalId) {
        this.receiverTerminalId = receiverTerminalId;
        return this;
    }

    public SendToAccount senderAccountId(String senderAccountId) {
        this.senderAccountId = senderAccountId;
        return this;
    }

    public SendToAccount description(String description) {
        this.description = description;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId + "/transactions";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (receiverTerminalId != null) {
                put("receiver_terminal_id", receiverTerminalId);
            }
            if (senderAccountId != null) {
                put("sender_account_id", senderAccountId);
            }
            if (amount != null) {
                put("amount", amount);
            }
            if (description != null) {
                put("description", description);
            }
        }};
    }

    public final UserTransaction send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(UserTransaction.class, accessToken);
    }
}
