// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class TopupWithCreditCard extends BankRequest {
    private String accountId;
    private Integer amount;
    private String cardRegisteredAt;
    private String cardUuid;
    private String organizationCode;
    private String userId;

    public TopupWithCreditCard(String userId, String accountId, int amount) {
        this.userId = userId;
        this.accountId = accountId;
        this.amount = amount;
    }

    public TopupWithCreditCard cardRegisteredAt(String cardRegisteredAt) {
        this.cardRegisteredAt = cardRegisteredAt;
        return this;
    }

    public TopupWithCreditCard cardUuid(String cardUuid) {
        this.cardUuid = cardUuid;
        return this;
    }

    public TopupWithCreditCard organizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/users" + "/" + this.userId + "/cards" + "/topup";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (amount != null) {
                put("amount", amount);
            }
            if (cardRegisteredAt != null) {
                put("card_registered_at", cardRegisteredAt);
            }
            if (cardUuid != null) {
                put("card_uuid", cardUuid);
            }
            if (organizationCode != null) {
                put("organization_code", organizationCode);
            }
        }};
    }

    public final UserTransaction send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(UserTransaction.class, accessToken);
    }
}
