// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;

public class TopupWithCreditCardMdkToken extends BankRequest {
    private String userId;
    private String token;
    private String accountId;
    private Integer amount;
    private String requestId;
    private String organizationCode;
    private Boolean isCardholderNameSpecified;

    public TopupWithCreditCardMdkToken(String userId, String token, String accountId, Integer amount, String requestId, String organizationCode) {
        this.userId = userId;
        this.token = token;
        this.accountId = accountId;
        this.amount = amount;
        this.requestId = requestId;
        this.organizationCode = organizationCode;
    }

    public TopupWithCreditCardMdkToken isCardholderNameSpecified(Boolean cardholderNameSpecified) {
        isCardholderNameSpecified = cardholderNameSpecified;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.POST;
    }

    @Override
    public String path() {
        return "/veritrans" + "/card-authorize" + "/topup-with-mdk-token";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (userId != null) {
                put("user_id", userId);
            }
            if (token != null) {
                put("token", token);
            }
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (amount != null) {
                put("amount", amount);
            }
            if (requestId != null) {
                put("request_id", requestId);
            }
            if (organizationCode != null) {
                put("organization_code", organizationCode);
            }
            if (isCardholderNameSpecified != null) {
                put("is_cardholder_name_specified", isCardholderNameSpecified);
            }
        }};
    }

    public final String send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(String.class, accessToken);
    }
}
