// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class UpdateCashtray extends BankRequest {
    private Integer amount;
    private String description;
    private Integer expiresIn;
    private Product[] products;
    private String cashtrayId;

    public UpdateCashtray(String cashtrayId) {
        this.cashtrayId = cashtrayId;
    }

    public UpdateCashtray amount(Integer amount) {
        this.amount = amount;
        return this;
    }

    public UpdateCashtray description(String description) {
        this.description = description;
        return this;
    }

    public UpdateCashtray expiresIn(Integer expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }

    public UpdateCashtray products(Product[] products) {
        this.products = products;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.PATCH;
    }

    @Override
    public String path() {
        return "/cashtrays" + "/" + this.cashtrayId;
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (amount != null) {
                put("amount", amount);
            }
            if (description != null) {
                put("description", description);
            }
            if (expiresIn != null) {
                put("expires_in", expiresIn);
            }
            if (products != null) {
                put("products", products);
            }
        }};
    }

    public final Cashtray send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(Cashtray.class, accessToken);
    }
}
