// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class UpdateAccount extends BankRequest {
    private String name;
    private Uuid accountId;

    public UpdateAccount(Uuid accountId) {
        this.accountId = accountId;
    }

    public UpdateAccount name(String name) {
        this.name = name;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.PATCH;
    }

    @Override
    public String path() {
        return "/accounts" + "/" + this.accountId;
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (name != null) {
                put("name", name);
            }
        }};
    }

    public final AccountDetail send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(AccountDetail.class, accessToken);
    }
}
