// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class UpdateTerminal extends BankRequest {
    private String name;
    private String accountId;
    private String pushService;
    private String pushToken;

    public UpdateTerminal() {
    }

    public UpdateTerminal name(String name) {
        this.name = name;
        return this;
    }

    public UpdateTerminal accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    public UpdateTerminal pushService(String pushService) {
        this.pushService = pushService;
        return this;
    }

    public UpdateTerminal pushToken(String pushToken) {
        this.pushToken = pushToken;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.PATCH;
    }

    @Override
    public String path() {
        return "/terminal";
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (name != null) {
                put("name", name);
            }
            if (accountId != null) {
                put("account_id", accountId);
            }
            if (pushService != null) {
                put("push_service", pushService);
            }
            if (pushToken != null) {
                put("push_token", pushToken);
            }
        }};
    }

    public final Terminal send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(Terminal.class, accessToken);
    }
}
