// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.requests;

import java.util.HashMap;
import java.util.Map;

import jp.pokepay.pokepaylib.BankAPI.BankRequest;
import jp.pokepay.pokepaylib.BankAPI.BankRequestError;
import jp.pokepay.pokepaylib.ProcessingError;
import jp.pokepay.pokepaylib.Request;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;

public class UpdateBill extends BankRequest {
    private Integer amount;
    private String description;
    private Product[] products;
    private String billId;

    public UpdateBill(String billId) {
        this.billId = billId;
    }

    public UpdateBill amount(Integer amount) {
        this.amount = amount;
        return this;
    }

    public UpdateBill description(String description) {
        this.description = description;
        return this;
    }

    public UpdateBill products(Product[] products) {
        this.products = products;
        return this;
    }

    @Override
    protected final Request.Method method() {
        return Request.Method.PATCH;
    }

    @Override
    public String path() {
        return "/bills" + "/" + this.billId;
    }

    @Override
    protected final Map<String, Object> parameters() {
        return new HashMap<String, Object>() {{
            if (amount != null) {
                put("amount", amount);
            }
            if (description != null) {
                put("description", description);
            }
            if (products != null) {
                put("products", products);
            }
        }};
    }

    public final Bill send(String accessToken) throws ProcessingError, BankRequestError {
        return super.send(Bill.class, accessToken);
    }
}
