// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class AccountCampaignPointAmounts extends Response {
    public Double max_total_point_amount;
    public Double total_point_amount;
    public Double remain_point_amount;
}

