// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class Account extends Response {
    public String id;
    public String name;
    public Double balance;
    public Double money_balance;
    public Double point_balance;
    public Double point_debt;
    public Boolean is_suspended;
    public PrivateMoney private_money;
}

