// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class AccountTopupStats extends Response {
    public Double current_amount;
    public Double limit_amount;
    public Double remaining_amount;
    public String started_at;
}

