// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class AccountBalance extends Response {
    public String expires_at;
    public Double money_amount;
    public Double point_amount;
}

