// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class AccountDetail extends Response {
    public String id;
    public String name;
    public Double balance;
    public Double money_balance;
    public Double point_balance;
    public Boolean is_suspended;
    public PrivateMoneyDetail private_money;
    public String nearest_expires_at;
}

