// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class BankPaySession extends Response {
    public String redirect_url;
    public String paytree_customer_number;
}

