// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;
import com.fasterxml.jackson.annotation.JsonProperty;

public class BankPaySession extends Response {
    @JsonProperty("redirectUrl")
    public String redirect_url;
    @JsonProperty("paytreeCustomerNumber")
    public String paytree_customer_number;
}

