// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class Bill extends Response {
    public String id;
    public Double amount;
    public String description;
    public User user;
    public Boolean is_onetime;
    public Boolean is_disabled;
    public PrivateMoney private_money;
    public String token;
    public Double max_amount;
    public Double min_amount;
}

