// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class Cashtray extends Response {
    public String id;
    public Double amount;
    public String description;
    public User user;
    public PrivateMoney private_money;
    public String expires_at;
    public String canceled_at;
    public String token;
}

