// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class CashtrayAttempt extends Response {
    public User user;
    public Account account;
    public Double status_code;
    public String error_type;
    public String error_message;
    public String created_at;
    public String strategy;
}

