// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class CashtrayAttempts extends Response {
    public CashtrayAttempt[] rows;
}

