// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class Check extends Response {
    public String id;
    public Double amount;
    public Double money_amount;
    public Double point_amount;
    public String description;
    public User user;
    public Boolean is_onetime;
    public Boolean is_disabled;
    public String expires_at;
    public PrivateMoney private_money;
    public String token;
}

