// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class Coupon extends Response {
    public String id;
    public String name;
    public String description;
    public Double discount_amount;
    public Double discount_percentage;
    public String starts_at;
    public String ends_at;
    public String display_starts_at;
    public String display_ends_at;
    public Double usage_limit;
    public Double min_amount;
    public Boolean is_shop_specified;
    public Boolean is_disabled;
    public Boolean is_hidden;
    public String coupon_image;
}

