// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class CpmToken extends Response {
    public String cpm_token;
    public Account account;
    public UserTransaction transaction;
    public String[] scopes;
    public String expires_at;
    public String metadata;
}

