// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class CVSAuthorization extends Response {
    public String id;
    public String service_option_type;
    public Integer amount;
    public String name1;
    public String name2;
    public String tel;
    public String pay_limit;
    public Account account;
}

