// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class DetailedShopInformation extends Response {
    public String id;
    public String name;
    public UserTagInformation[] tags;
    public String business_hours;
    public String regular_closed_days;
    public String url;
    public String logo_image_url;
    public String[] image_urls;
    public String address;
    public String tel;
}

