// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class IdentificationResult extends Response {
    public Boolean is_valid;
    public String identified_at;
    public Object match;
}

