// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class IdentificationMatch extends Response {
    public Boolean name;
    public Boolean gender;
    public Boolean address;
    public Boolean date_of_birth;
}

