// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class IndividualNumberIdentificationError extends Response {
    public String type;
    public String message;
    public Integer error_code;
    public String error_message;
}

