// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class IndividualNumberIdentificationStatus extends Response {
    public Boolean is_valid;
    public String last_identified_at;
    public String expires_at;
    public Boolean is_resident;
}

