// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class JihanpiVendingMachine extends Response {
    public String nfc_tag_id;
    public String shop_id;
    public String shop_name;
}

