// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class JihanpiTransaction extends Response {
    public String order_id;
    public Nil transaction;
    public Account account;
    public JihanpiVendingMachine vending_machine_info;
    public String state;
    public String error_reason;
    public String strategy;
}

