// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class PaginatedCreditCards extends Response {
    public Integer per_page;
    public Integer count;
    public String next;
    public String prev;
    public CreditCard[] items;
}

