// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class PrivateMoneyTopupMethod extends Response {
    public String type;
    public String name;
    public Double[] amounts;
    public Double[] range;
}

