// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class PrivateMoney extends Response {
    public String id;
    public String name;
    public String type;
    public String unit;
    public String description;
    public String oneline_message;
    public String display_money_and_point;
    public String account_image;
    public PrivateMoneyImages images;
    public Organization organization;
    public Double max_balance;
    public Double transfer_limit;
    public String expiration_type;
    public Boolean is_exclusive;
    public String terms_url;
    public String privacy_policy_url;
    public String payment_act_url;
    public String commercial_act_url;
}

