// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PrivateMoneyImages extends Response {
    public String card;
    @JsonProperty("300x300")
    public String n300x300;
    @JsonProperty("600x600")
    public String n600x600;
}

