// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class Product extends Response {
    public String jan_code;
    public String name;
    public Double unit_price;
    public Double price;
    public Integer quantity;
    public Boolean is_discounted;
    public String other;
}

