// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class SevenBankAtmSession extends Response {
    public String qr_info;
    public Account account;
    public Integer amount;
    public UserTransactionWithTransfers transaction;
}

