// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class ShopInformation extends Response {
    public String id;
    public String name;
    public UserTagInformation[] tags;
    public String logo_image_url;
}

