// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class Terminal extends Response {
    public String id;
    public String name;
    public String hardware_id;
    public String push_service;
    public String push_token;
    public UserWithDetails user;
    public Nil account;
}

