// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class UserBank extends Response {
    public String id;
    public PrivateMoney private_money;
    public String bank_name;
    public String bank_code;
    public String branch_number;
    public String branch_name;
    public String deposit_type;
    public String masked_account_number;
    public String account_name;
}

