// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class UserTransferWithoutAccount extends Response {
    public String id;
    public Double amount;
    public Double money_amount;
    public Double point_amount;
    public String description;
    public String done_at;
    public String type;
}

