// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class UserTagSubgroup extends Response {
    public String subgroup_name;
    public String id;
}

