// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepaylib.BankAPI.autogen.responses;

import jp.pokepay.pokepaylib.Response;

public class UserWithDetails extends Response {
    public String id;
    public String name;
    public Boolean is_merchant;
    public String tel;
    public String email;
}

